dataset: "RUSLAN"

path:
  corpus_path: "/content/drive/MyDrive/mydata"
  lexicon_path: "lexicon/russian_mfa.dict"
  raw_path: "/content/drive/MyDrive/FastSpeech2-ru/raw_data/RUSLAN"
  preprocessed_path: "/content/drive/MyDrive/FastSpeech2-ru/preprocessed_data/RUSLAN" # "/content/preprocessed_data/RUSLAN"  #

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["basic_cleaners"]
    language: "ru"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
